# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "docker" do |d|
    d.run "vfarcic/cd_jenkins",
      args: "-d -p 0.0.0.0:49153:8080"
  end
end
